language: node_js

node_js:
  - '7'
  - '6'
  - '4'

cache:
  yarn: true

before_install:
  - npm install shelljs
  - ./sync-fork-before

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - ./sync-fork-after
